version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: niveshya-mongo
    restart: unless-stopped
    profiles:
      - embedded-mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: niveshya-backend
    restart: unless-stopped
    environment:
      - mongodb_url=${MONGODB_URL:-mongodb://mongo:27017}
      - database_name=${database_name:-trackon_lead_management}
      - environment=production
      - debug=false
      - write_compat_tnifmc_fields=true
      - response_include_both_field_names=true
      - CORS_ORIGINS=${CORS_ORIGINS}
    volumes:
      - uploads:/app/uploads
    # No hard depends_on, to allow connecting to external/host MongoDB
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: niveshya-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  mongo_data:
  uploads:

networks:
  appnet:
    driver: bridge
